Add CI to run tests
emseers/eelbot-framework pull request #2
Opened 2021-04-30 02:34 UTC by boarnoah

2021-04-30 03:19 UTC, boarnoah commented
Hm, that summary isn't the greatest eh. like the wording and stuff

2021-04-30 12:41 UTC, TheRightMouse commented on .github/workflows/ci.yml
> +          cmake --build . --
If you're not passing in any args to `build` (such as `-j12` etc.) you can omit the trailing `--`.

2021-04-30 12:44 UTC, TheRightMouse commented
Is it possible to have the tests results show up at the top of the README?

2021-04-30 21:09 UTC, boarnoah commented
> Is it possible to have the tests results show up at the top of the README?

You mean badge for default branch's status?

2021-04-30 21:24 UTC, boarnoah commented
As we found out, you can click on a github action and choose to generate a test badge and use that in readmes etc..

2021-05-01 20:07 UTC, TheRightMouse approved these changes
Looks good to me.

2021-05-09 16:52 UTC, aashkir requested changes
Looks good, but it should be called: Continuous, not Continous (On line 1)

2021-05-10 01:56 UTC, boarnoah commented
Mouse pointed out in chat he would like to see int he future separate badges for windows vs linux statuses, with github actions that likely means separate workflows (since 1 workflow = 1 badge).

When/if we do that then this would be renamed to CI linux etc.. to make that fact clear

2021-05-10 21:39 UTC, aashkir approved these changes
Nice work.

2021-05-10 21:40 UTC, merged